
Imports BL
Imports System.Windows.Forms
Imports DevExpress.XtraGrid.Views.Grid

Public Class PurchaseOrderClose

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub PurchaseOrderClose_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.Space And e.Control = True Then
                'SELECT ALL DATA
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = Not Convert.ToBoolean(dtrow("CLOSED"))
                Next
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub PurchaseOrderClose_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'PURCHASE ORDER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal TEMPCONDITION)
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable = objclsCMST.search("*", "", " (SELECT PURCHASEORDER.PO_NO AS PONO, PURCHASEORDER.PO_DATE AS PODATE, PURCHASEORDER.PO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(PURCHASEORDER.PO_CRDAYS, 0) AS CRDAYS, ISNULL(PURCHASEORDER.PO_DELDAYS, 0) AS DELDAYS, ISNULL(PURCHASEORDER.PO_REFNO, '0') AS REFNO, ISNULL(PURCHASEORDER.PO_DISCOUNT, 0) AS DISCOUNT, ISNULL(PURCHASEORDER.PO_QUOTNO, 0) AS QUOTNO, PURCHASEORDER.PO_QUOTDATE AS QUOTDATE, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(PURCHASEORDER.PO_REMARKS, '') AS REMARKS, ISNULL(PURCHASEORDER.PO_DONE, 0) AS PODONE, PURCHASEORDER_DESC.PO_GRIDSRNO AS POGRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(PURCHASEORDER_DESC.PO_GRIDREMARKS, '') AS GRIDREMARKS, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(PURCHASEORDER_DESC.PO_REED, 0) AS REED, ISNULL(PURCHASEORDER_DESC.PO_PICK, 0) AS PICK, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ISNULL(PURCHASEORDER_DESC.PO_PDESNO, '') AS PDESNO, ISNULL(PURCHASEORDER_DESC.PO_PSHADE, '') AS PSHADE, ISNULL(PURCHASEORDER_DESC.PO_CUT, 0) AS CUT, ISNULL(PURCHASEORDER_DESC.PO_QTY, 0) AS QTY, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(PURCHASEORDER_DESC.PO_MTRS, 0) AS MTRS, ISNULL(PURCHASEORDER_DESC.PO_RATE, 0) AS RATE, ISNULL(PURCHASEORDER_DESC.PO_AMT, 0) AS AMT, ISNULL(PURCHASEORDER_DESC.PO_QUOTNO, 0) AS GRIDQUOTNO, PURCHASEORDER_DESC.PO_QUOTGRIDSRNO AS QUOTGRIDSRNO, ISNULL(PURCHASEORDER_DESC.PO_RECDQTY, 0) AS RECDQTY, ISNULL(PURCHASEORDER_DESC.PO_RECDMTRS, 0) AS RECDMTRS, ISNULL(PURCHASEORDER_DESC.PO_DONE, 0) AS GRIDPODONE, ISNULL(PURCHASEORDER.PO_AMENDNO, '0') AS AMDNO, ISNULL(PURCHASEORDER.PO_AMENDDONE, 0) AS AMDDONE, ISNULL(PURCHASEORDER.PO_DISPER, 0) AS PO_DISPER, ISNULL(PURCHASEORDER.PO_DISAMT, 0) AS PO_DISAMT, ISNULL(PURCHASEORDER.PO_PFPER, 0) AS PO_PFPER, ISNULL(PURCHASEORDER.PO_PFAMT, 0) AS PO_PFAMT, ISNULL(PURCHASEORDER.PO_TESTCHGS, 0) AS PO_TESTCHGS, ISNULL(PURCHASEORDER.PO_NETT, 0) AS PO_NETT, ISNULL(PURCHASEORDER.PO_SUBTOTAL, 0) AS PO_SUBTOTAL, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(PURCHASEORDER.PO_TAXAMT, 0) AS PO_TAXAMT, ISNULL(ADDTAXMASTER.tax_name, '') AS ADDTAXNAME, ISNULL(PURCHASEORDER.PO_ADDTAXAMT, 0) AS PO_ADDTAXAMT, ISNULL(PURCHASEORDER.PO_FRPER, 0) AS PO_FRPER, ISNULL(PURCHASEORDER.PO_FREIGHT, 0) AS PO_FREIGHT, ISNULL(OCTROIMASTER.OCTROI_name, '') AS OCTROINAME, ISNULL(PURCHASEORDER.PO_OCTROIAMT, 0) AS PO_OCTROIAMT, ISNULL(PURCHASEORDER.PO_INSAMT, 0) AS PO_INSAMT, ISNULL(PURCHASEORDER.PO_ROUNDOFF, 0) AS PO_ROUNDOFF, ISNULL(PURCHASEORDER.PO_GRANDTOTAL, 0) AS PO_GRANDTOTAL, ISNULL(PURCHASEORDER_DESC.PO_count, 0) AS COUNT, ISNULL(PURCHASEORDER_DESC.PO_WIDTH, 0) AS WIDTH, ISNULL(PURCHASEORDER_DESC.PO_WT, 0) AS WT, ISNULL(PURCHASEORDER_DESC.PO_PER, '0') AS PER, ISNULL(TOLEDGERS.Acc_cmpname, '') AS TONAME, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(PURCHASEORDER.PO_VERIFIED, 0) AS VERIFIED, ISNULL(PURCHASEORDER.PO_SMSSEND, 0) AS SMSSEND, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(PURCHASEORDER.PO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(PURCHASEORDER_DESC.PO_CLOSED, 0) AS CLOSED, (PURCHASEORDER_DESC.PO_QTY-PURCHASEORDER_DESC.PO_RECDQTY) AS BALPCS, (PURCHASEORDER_DESC.PO_MTRS-PURCHASEORDER_DESC.PO_RECDMTRS) AS BALMTRS, 'PURCHASEORDER' AS TYPE FROM PURCHASEORDER INNER JOIN PURCHASEORDER_DESC ON PURCHASEORDER.PO_NO = PURCHASEORDER_DESC.PO_NO AND PURCHASEORDER.PO_YEARID = PURCHASEORDER_DESC.PO_YEARID INNER JOIN ITEMMASTER ON PURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON PURCHASEORDER_DESC.PO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON PURCHASEORDER.PO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON PURCHASEORDER_DESC.PO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON PURCHASEORDER.PO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TOLEDGERS ON PURCHASEORDER_DESC.PO_TOLEDGERID = TOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON PURCHASEORDER.PO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON PURCHASEORDER_DESC.PO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN OCTROIMASTER ON PURCHASEORDER.PO_OCTROIID = OCTROIMASTER.OCTROI_id LEFT OUTER JOIN TAXMASTER AS ADDTAXMASTER ON PURCHASEORDER.PO_ADDTAXID = ADDTAXMASTER.tax_id LEFT OUTER JOIN TAXMASTER AS TAXMASTER ON PURCHASEORDER.PO_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN COLORMASTER ON PURCHASEORDER_DESC.PO_COLORID = COLORMASTER.COLOR_id WHERE PURCHASEORDER_DESC.PO_CLOSED = 'FALSE' and (PURCHASEORDER_DESC.PO_MTRS-PURCHASEORDER_DESC.PO_RECDMTRS)>0 AND dbo.PURCHASEORDER.PO_yearid=" & YearId & " UNION ALL SELECT OPENINGPURCHASEORDER.OPO_NO AS PONO, OPENINGPURCHASEORDER.OPO_DATE AS PODATE, OPENINGPURCHASEORDER.OPO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(OPENINGPURCHASEORDER.OPO_CRDAYS, 0) AS CRDAYS, ISNULL(OPENINGPURCHASEORDER.OPO_DELDAYS, 0) AS DELDAYS, ISNULL(OPENINGPURCHASEORDER.OPO_REFNO, '0') AS REFNO, ISNULL(OPENINGPURCHASEORDER.OPO_DISCOUNT, 0) AS DISCOUNT, ISNULL(OPENINGPURCHASEORDER.OPO_QUOTNO, 0) AS QUOTNO, OPENINGPURCHASEORDER.OPO_QUOTDATE AS QUOTDATE, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(OPENINGPURCHASEORDER.OPO_REMARKS, '') AS REMARKS, ISNULL(OPENINGPURCHASEORDER.OPO_DONE, 0) AS PODONE, OPENINGPURCHASEORDER_DESC.OPO_GRIDSRNO AS POGRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_GRIDREMARKS, '') AS GRIDREMARKS, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_REED, 0) AS REED, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_PICK, 0) AS PICK, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_PDESNO, '') AS PDESNO, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_PSHADE, '') AS PSHADE, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_CUT, 0) AS CUT, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_QTY, 0) AS QTY, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_MTRS, 0) AS MTRS, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_RATE, 0) AS RATE, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_AMT, 0) AS AMT, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_QUOTNO, 0) AS GRIDQUOTNO, OPENINGPURCHASEORDER_DESC.OPO_QUOTGRIDSRNO AS QUOTGRIDSRNO, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_RECDQTY, 0) AS RECDQTY, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_RECDMTRS, 0) AS RECDMTRS, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_DONE, 0) AS GRIDPODONE, ISNULL(OPENINGPURCHASEORDER.OPO_AMENDNO, '0') AS AMDNO, ISNULL(OPENINGPURCHASEORDER.OPO_AMENDDONE, 0) AS AMDDONE, ISNULL(OPENINGPURCHASEORDER.OPO_DISPER, 0) AS OPO_DISPER, ISNULL(OPENINGPURCHASEORDER.OPO_DISAMT, 0) AS OPO_DISAMT, ISNULL(OPENINGPURCHASEORDER.OPO_PFPER, 0) AS OPO_PFPER, ISNULL(OPENINGPURCHASEORDER.OPO_PFAMT, 0) AS OPO_PFAMT, ISNULL(OPENINGPURCHASEORDER.OPO_TESTCHGS, 0) AS OPO_TESTCHGS, ISNULL(OPENINGPURCHASEORDER.OPO_NETT, 0) AS OPO_NETT, ISNULL(OPENINGPURCHASEORDER.OPO_SUBTOTAL, 0) AS OPO_SUBTOTAL, ISNULL(TAXMASTER.tax_name, '') AS TAXNAME, ISNULL(OPENINGPURCHASEORDER.OPO_TAXAMT, 0) AS OPO_TAXAMT, ISNULL(ADDTAXMASTER.tax_name, '') AS ADDTAXNAME, ISNULL(OPENINGPURCHASEORDER.OPO_ADDTAXAMT, 0) AS OPO_ADDTAXAMT, ISNULL(OPENINGPURCHASEORDER.OPO_FRPER, 0) AS OPO_FRPER, ISNULL(OPENINGPURCHASEORDER.OPO_FREIGHT, 0) AS OPO_FREIGHT, ISNULL(OCTROIMASTER.OCTROI_name, '') AS OCTROINAME, ISNULL(OPENINGPURCHASEORDER.OPO_OCTROIAMT, 0) AS OPO_OCTROIAMT, ISNULL(OPENINGPURCHASEORDER.OPO_INSAMT, 0) AS OPO_INSAMT, ISNULL(OPENINGPURCHASEORDER.OPO_ROUNDOFF, 0) AS OPO_ROUNDOFF, ISNULL(OPENINGPURCHASEORDER.OPO_GRANDTOTAL, 0) AS OPO_GRANDTOTAL, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_count, 0) AS COUNT, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_WIDTH, 0) AS WIDTH, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_WT, 0) AS WT, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_PER, '0') AS PER, ISNULL(TOLEDGERS.Acc_cmpname, '') AS TONAME, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(OPENINGPURCHASEORDER.OPO_VERIFIED, 0) AS VERIFIED, ISNULL(OPENINGPURCHASEORDER.OPO_SMSSEND, 0) AS SMSSEND, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(OPENINGPURCHASEORDER.OPO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_CLOSED, 0) AS CLOSED, (OPENINGPURCHASEORDER_DESC.OPO_QTY-OPENINGPURCHASEORDER_DESC.OPO_RECDQTY) AS BALPCS, (OPENINGPURCHASEORDER_DESC.OPO_MTRS-OPENINGPURCHASEORDER_DESC.OPO_RECDMTRS) AS BALMTRS, 'OPENING' AS TYPE FROM OPENINGPURCHASEORDER INNER JOIN OPENINGPURCHASEORDER_DESC ON OPENINGPURCHASEORDER.OPO_NO = OPENINGPURCHASEORDER_DESC.OPO_NO AND OPENINGPURCHASEORDER.OPO_YEARID = OPENINGPURCHASEORDER_DESC.OPO_YEARID INNER JOIN ITEMMASTER ON OPENINGPURCHASEORDER_DESC.OPO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGPURCHASEORDER_DESC.OPO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON OPENINGPURCHASEORDER.OPO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON OPENINGPURCHASEORDER_DESC.OPO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON OPENINGPURCHASEORDER.OPO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TOLEDGERS ON OPENINGPURCHASEORDER_DESC.OPO_TOLEDGERID = TOLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON OPENINGPURCHASEORDER.OPO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGPURCHASEORDER_DESC.OPO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN OCTROIMASTER ON OPENINGPURCHASEORDER.OPO_OCTROIID = OCTROIMASTER.OCTROI_id LEFT OUTER JOIN TAXMASTER AS ADDTAXMASTER ON OPENINGPURCHASEORDER.OPO_ADDTAXID = ADDTAXMASTER.tax_id LEFT OUTER JOIN TAXMASTER AS TAXMASTER ON OPENINGPURCHASEORDER.OPO_TAXID = TAXMASTER.tax_id LEFT OUTER JOIN COLORMASTER ON OPENINGPURCHASEORDER_DESC.OPO_COLORID = COLORMASTER.COLOR_id WHERE OPENINGPURCHASEORDER_DESC.OPO_CLOSED = 'FALSE' and (OPENINGPURCHASEORDER_DESC.OPO_MTRS-OPENINGPURCHASEORDER_DESC.OPO_RECDMTRS)>0 AND dbo.OPENINGPURCHASEORDER.OPO_yearid=" & YearId & ") AS T", " ORDER BY PONO, POGRIDSRNO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            Dim OBJCMN As New ClsCommon
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                    If DTROW("TYPE") = "PURCHASEORDER" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE PURCHASEORDER_DESC SET PO_CLOSED = 1 WHERE PO_NO = " & Val(DTROW("PONO")) & " AND PO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND PO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGPURCHASEORDER_DESC SET OPO_CLOSED = 1 WHERE OPO_NO = " & Val(DTROW("PONO")) & " AND OPO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND OPO_YEARID = " & YearId, "", "")
                End If
            Next
            MsgBox("Entries Updated")
            Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("CLOSED")) = "Checked" Then
                    e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Bold)
                    e.Appearance.BackColor = Color.Yellow
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PrintToolStripButton.Click
        Try

            Dim PATH As String = Application.StartupPath & "\Purchase Order Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Purchase Order Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Purchase Order Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Purchase Order Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub


End Class